"""Every Pawpado feature route, one method each — generated by apigen from
backend/openapi.json. Do not edit by hand; regenerate after the API changes.

Reach them as ``client.api.<area>_<action>(...)``. Each call goes through the
client's own ``_apigen_request`` (its sign-in and response envelope).
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


class GeneratedApi:
    """All 42 feature routes of the Pawpado API."""

    def __init__(self, client: Any) -> None:
        self._client = client

    def _call(self, method: str, path: str, query: Dict[str, Any], body: Optional[Dict[str, Any]]) -> Any:
        query = {k: v for k, v in query.items() if v is not None}
        return self._client._apigen_request(method, path, query=query or None, body=body)

    def account_delete(self, *, confirm: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Delete account (POST /api/v1/account/delete).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if confirm is not None:
            payload["confirm"] = confirm
        if "confirm" not in payload:
            raise ValueError("account_delete needs confirm")
        return self._call("POST", f"/api/v1/account/delete", {}, payload)

    def api_keys_create(self, *, name: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an api key (POST /api/v1/api-keys).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if "name" not in payload:
            raise ValueError("api_keys_create needs name")
        return self._call("POST", f"/api/v1/api-keys", {}, payload)

    def api_keys_delete(self, id_: str) -> Any:
        """Delete an api key (DELETE /api/v1/api-keys/{id})."""
        return self._call("DELETE", f"/api/v1/api-keys/{_q(id_)}", {}, None)

    def api_keys_list(self) -> Any:
        """List api keys (GET /api/v1/api-keys)."""
        return self._call("GET", f"/api/v1/api-keys", {}, None)

    def audit_log_list(self, *, cursor: Optional[str] = None, limit: Optional[float] = None, action: Optional[str] = None) -> Any:
        """The workspace's audit trail, newest first, cursor-paginated. (GET /api/v1/audit-log)."""
        return self._call("GET", f"/api/v1/audit-log", {"cursor": cursor, "limit": limit, "action": action}, None)

    def billing_create_storage(self, *, storage_gb: Optional[int] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Grow the workspace's disk to storageGb (owner/admin). (POST /api/v1/billing/storage).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if storage_gb is not None:
            payload["storageGb"] = storage_gb
        if "storageGb" not in payload:
            raise ValueError("billing_create_storage needs storage_gb")
        return self._call("POST", f"/api/v1/billing/storage", {}, payload)

    def billing_storage(self) -> Any:
        """The storage sizes on offer (presets, min, max GB). (GET /api/v1/billing/storage)."""
        return self._call("GET", f"/api/v1/billing/storage", {}, None)

    def credits_create_topup(self, *, amount_idr: Optional[float] = None, amount_usd_cents: Optional[int] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Start a checkout that tops up the workspace's wallet (amountIdr, or amountUsdCents for PayPal/USD). (POST /api/v1/credits/topup).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if amount_idr is not None:
            payload["amountIdr"] = amount_idr
        if amount_usd_cents is not None:
            payload["amountUsdCents"] = amount_usd_cents
        return self._call("POST", f"/api/v1/credits/topup", {}, payload)

    def credits_me(self) -> Any:
        """The workspace's wallet and its 25 latest transactions. (GET /api/v1/credits/me)."""
        return self._call("GET", f"/api/v1/credits/me", {}, None)

    def credits_topup(self) -> Any:
        """The top-up amounts on offer (IDR presets and range; USD cents). (GET /api/v1/credits/topup)."""
        return self._call("GET", f"/api/v1/credits/topup", {}, None)

    def feedback_create(self, *, session_id: Optional[str] = None, rating: Optional[int] = None, experience: Optional[str] = None, games_played: Optional[str] = None, game_wanted: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """The optional post-session survey. (POST /api/v1/feedback).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if session_id is not None:
            payload["sessionId"] = session_id
        if rating is not None:
            payload["rating"] = rating
        if experience is not None:
            payload["experience"] = experience
        if games_played is not None:
            payload["gamesPlayed"] = games_played
        if game_wanted is not None:
            payload["gameWanted"] = game_wanted
        if "sessionId" not in payload:
            raise ValueError("feedback_create needs session_id")
        if "rating" not in payload:
            raise ValueError("feedback_create needs rating")
        return self._call("POST", f"/api/v1/feedback", {}, payload)

    def feedback_list(self, *, session_id: str) -> Any:
        """Has this session been answered yet? (GET /api/v1/feedback)."""
        return self._call("GET", f"/api/v1/feedback", {"sessionId": session_id}, None)

    def machines_config(self, *, streaming_quality: Optional[str] = None, concurrent_streams: Optional[float] = None, machine_tier: Optional[str] = None, machine_image: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Change the streaming quality, the concurrent-stream (local-multiplayer) count, the product tier, and/or the baked image a Custom machine is built from, for the workspace member. (POST /api/v1/machines/config).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if streaming_quality is not None:
            payload["streamingQuality"] = streaming_quality
        if concurrent_streams is not None:
            payload["concurrentStreams"] = concurrent_streams
        if machine_tier is not None:
            payload["machineTier"] = machine_tier
        if machine_image is not None:
            payload["machineImage"] = machine_image
        return self._call("POST", f"/api/v1/machines/config", {}, payload)

    def machines_create(self, *, instance_type: Optional[str] = None, streaming_quality: Optional[str] = None, storage_gb: Optional[float] = None, region: Optional[str] = None, concurrent_streams: Optional[float] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Persist the machine configuration chosen in the "build your machine" form. (POST /api/v1/machines).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if instance_type is not None:
            payload["instanceType"] = instance_type
        if streaming_quality is not None:
            payload["streamingQuality"] = streaming_quality
        if storage_gb is not None:
            payload["storageGb"] = storage_gb
        if region is not None:
            payload["region"] = region
        if concurrent_streams is not None:
            payload["concurrentStreams"] = concurrent_streams
        if "instanceType" not in payload:
            raise ValueError("machines_create needs instance_type")
        if "streamingQuality" not in payload:
            raise ValueError("machines_create needs streaming_quality")
        if "storageGb" not in payload:
            raise ValueError("machines_create needs storage_gb")
        return self._call("POST", f"/api/v1/machines", {}, payload)

    def machines_delete(self) -> Any:
        """Delete the workspace's one computer. (DELETE /api/v1/machines)."""
        return self._call("DELETE", f"/api/v1/machines", {}, None)

    def machines_resize(self, *, instance_type: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Change the machine's CPU & RAM tier (g5.xlarge ↔ g5.2xlarge ↔ g5.4xlarge) in place. (POST /api/v1/machines/resize).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if instance_type is not None:
            payload["instanceType"] = instance_type
        if "instanceType" not in payload:
            raise ValueError("machines_resize needs instance_type")
        return self._call("POST", f"/api/v1/machines/resize", {}, payload)

    def onboarding_acknowledge(self) -> Any:
        """Record that the setup checklist was seen, for the signed-in person (or, with an API key, the person who made the key). (POST /api/v1/onboarding/acknowledge)."""
        return self._call("POST", f"/api/v1/onboarding/acknowledge", {}, None)

    def sessions_connect(self) -> Any:
        """How to reach the workspace's running machine: its public address, tailnet address, RDP and Apollo credentials, client download links. (GET /api/v1/sessions/connect)."""
        return self._call("GET", f"/api/v1/sessions/connect", {}, None)

    def sessions_create_tailscale_key(self) -> Any:
        """Return the auth key the user pastes (or scans via QR) into the Tailscale app on their iPad/phone so the device joins our tailnet under tag:pawpado-user. (POST /api/v1/sessions/tailscale-key)."""
        return self._call("POST", f"/api/v1/sessions/tailscale-key", {}, None)

    def sessions_pair(self, *, pin: Optional[str] = None, device_name: Optional[str] = None, via: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Pair a Moonlight client with the running machine: send the 4-digit PIN Moonlight shows. (POST /api/v1/sessions/pair).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        via: one of desktop, mobile"""
        payload: Dict[str, Any] = dict(json_body or {})
        if pin is not None:
            payload["pin"] = pin
        if device_name is not None:
            payload["deviceName"] = device_name
        if via is not None:
            payload["via"] = via
        if "pin" not in payload:
            raise ValueError("sessions_pair needs pin")
        return self._call("POST", f"/api/v1/sessions/pair", {}, payload)

    def sessions_poll(self) -> Any:
        """The browser's view of the session state machine. (GET /api/v1/sessions/poll)."""
        return self._call("GET", f"/api/v1/sessions/poll", {}, None)

    def sessions_start(self) -> Any:
        """Start session (POST /api/v1/sessions/start)."""
        return self._call("POST", f"/api/v1/sessions/start", {}, None)

    def sessions_stop(self, *, force: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Stop session (POST /api/v1/sessions/stop).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if force is not None:
            payload["force"] = force
        return self._call("POST", f"/api/v1/sessions/stop", {}, payload)

    def sessions_tailscale_key(self) -> Any:
        """Return the auth key the user pastes (or scans via QR) into the Tailscale app on their iPad/phone so the device joins our tailnet under tag:pawpado-user. (GET /api/v1/sessions/tailscale-key)."""
        return self._call("GET", f"/api/v1/sessions/tailscale-key", {}, None)

    def settings_client_prefs(self) -> Any:
        """Get settings client prefs (GET /api/v1/settings/client-prefs)."""
        return self._call("GET", f"/api/v1/settings/client-prefs", {}, None)

    def settings_list(self) -> Any:
        """List settings (GET /api/v1/settings)."""
        return self._call("GET", f"/api/v1/settings", {}, None)

    def settings_update(self, *, idle_auto_stop_minutes: Optional[float] = None, play_mode: Optional[str] = None, launch_options: Optional[Dict[str, Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update settings (PATCH /api/v1/settings).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if idle_auto_stop_minutes is not None:
            payload["idleAutoStopMinutes"] = idle_auto_stop_minutes
        if play_mode is not None:
            payload["playMode"] = play_mode
        if launch_options is not None:
            payload["launchOptions"] = launch_options
        return self._call("PATCH", f"/api/v1/settings", {}, payload)

    def settings_update_client_prefs(self, *, client_prefs: Optional[Dict[str, Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """The 23 settings the stream URL cannot carry. (PATCH /api/v1/settings/client-prefs).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if client_prefs is not None:
            payload["clientPrefs"] = client_prefs
        if "clientPrefs" not in payload:
            raise ValueError("settings_update_client_prefs needs client_prefs")
        return self._call("PATCH", f"/api/v1/settings/client-prefs", {}, payload)

    def snapshots_create(self, *, name: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a snapshot of the caller's machine. (POST /api/v1/snapshots).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if "name" not in payload:
            raise ValueError("snapshots_create needs name")
        return self._call("POST", f"/api/v1/snapshots", {}, payload)

    def snapshots_delete(self, id_: str) -> Any:
        """Delete the AWS EBS snapshot + the row. (DELETE /api/v1/snapshots/{id})."""
        return self._call("DELETE", f"/api/v1/snapshots/{_q(id_)}", {}, None)

    def snapshots_list(self) -> Any:
        """List this workspace's snapshots (newest first). (GET /api/v1/snapshots)."""
        return self._call("GET", f"/api/v1/snapshots", {}, None)

    def snapshots_restore(self, id_: str) -> Any:
        """Roll the caller's machine back to this snapshot. (POST /api/v1/snapshots/{id}/restore)."""
        return self._call("POST", f"/api/v1/snapshots/{_q(id_)}/restore", {}, None)

    def snapshots_status(self, id_: str) -> Any:
        """Live creation progress for one snapshot, workspace-scoped. (GET /api/v1/snapshots/{id}/status)."""
        return self._call("GET", f"/api/v1/snapshots/{_q(id_)}/status", {}, None)

    def stream_apps(self) -> Any:
        """What the Play grid renders. (GET /api/v1/stream/apps)."""
        return self._call("GET", f"/api/v1/stream/apps", {}, None)

    def webhooks_create(self, *, url: Optional[str] = None, events: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Add a subscription: an https `url` (not a private, loopback or link-local address) and `events` — "*", event types from GET /api/v1/webhooks/event-types, or prefixes like "pawpado.session.*" (default  (POST /api/v1/webhooks).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if url is not None:
            payload["url"] = url
        if events is not None:
            payload["events"] = events
        return self._call("POST", f"/api/v1/webhooks", {}, payload)

    def webhooks_delete(self, id_: str) -> Any:
        """Remove a subscription (and its delivery log). (DELETE /api/v1/webhooks/{id})."""
        return self._call("DELETE", f"/api/v1/webhooks/{_q(id_)}", {}, None)

    def webhooks_deliveries(self, *, limit: Optional[int] = None, status: Optional[str] = None, cursor: Optional[str] = None, subscription_id: Optional[str] = None, type_: Optional[str] = None) -> Any:
        """The delivery log, newest first: one row per event per subscription, with its status (pending, succeeded, failed), attempt count, next retry, the body sent (`payload`) and every attempt made (`attemptL (GET /api/v1/webhooks/deliveries)."""
        return self._call("GET", f"/api/v1/webhooks/deliveries", {"limit": limit, "status": status, "cursor": cursor, "subscriptionId": subscription_id, "type": type_}, None)

    def webhooks_deliveries_retry(self, delivery_id: str) -> Any:
        """One more attempt now, at a failed delivery (or to send a succeeded one again). (POST /api/v1/webhooks/deliveries/{deliveryId}/retry)."""
        return self._call("POST", f"/api/v1/webhooks/deliveries/{_q(delivery_id)}/retry", {}, None)

    def webhooks_event_types(self) -> Any:
        """Every event type Pawpado delivers, with what it means: what a subscription's `events` can name (besides "*" and prefixes such as "pawpado.session.*"). (GET /api/v1/webhooks/event-types)."""
        return self._call("GET", f"/api/v1/webhooks/event-types", {}, None)

    def webhooks_get_deliveries(self, delivery_id: str) -> Any:
        """One delivery, with every attempt made at it. (GET /api/v1/webhooks/deliveries/{deliveryId})."""
        return self._call("GET", f"/api/v1/webhooks/deliveries/{_q(delivery_id)}", {}, None)

    def webhooks_list(self) -> Any:
        """The workspace's webhook subscriptions, each with its failure streak (consecutiveFailures, failingSince) and, when Pawpado switched it off for failing, disabledAt and disabledReason. (GET /api/v1/webhooks)."""
        return self._call("GET", f"/api/v1/webhooks", {}, None)

    def webhooks_update(self, id_: str, *, url: Optional[str] = None, events: Optional[Any] = None, active: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Change a subscription: `url`, `events`, `active` (only the ones given). (PATCH /api/v1/webhooks/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if url is not None:
            payload["url"] = url
        if events is not None:
            payload["events"] = events
        if active is not None:
            payload["active"] = active
        return self._call("PATCH", f"/api/v1/webhooks/{_q(id_)}", {}, payload)


def _q(value: Any) -> str:
    from urllib.parse import quote

    return quote(str(value), safe="")
